{% set name = "apache-airflow-providers-facebook" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c400bd8994eb3b5fdee61c3a5e903656a76ae33267296f1872d94d4cca8327be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.9.0
    - facebook_business >=15.0.2

test:
  imports:
    - airflow.providers.facebook
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-facebook for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/facebook/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-facebook/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
